Repository pythonpune/meetup-talks, pull requests merged in 2019-11, with the labels that each got.

#66 Added Nov PythonPune newsletter
  2019/November/community_news.md
Labels: newsletter

#71 Moving CI checks to GitHub action
  .github/workflows/main.yml
  .travis.yml
Labels: enhancement

#72 Add details of November 2019 meetup
  2019/November/README.md
  README.md
Labels: Talks
